---
resources: "{{POPPY_UU_HOME}}/config/resources.yaml"
samples: "samples.tsv"
units: "units.tsv"
output: "{{POPPY_UU_HOME}}/config/output_files.yaml"

reference:
  fasta: "/data/ref_genomes/GRCh38/GRCmasked/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta"
  fai: "/data/ref_genomes/GRCh38/GRCmasked/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.fai"
  dict: "/data/ref_genomes/GRCh38/GRCmasked/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.dict"
  exon_bed: "/projects/wp2/nobackup/Twist_Myeloid/Bed_files/HG38/Twist_myeloid_coding_exons_added_regions.250904.bed"
  design_bed: "/projects/wp2/nobackup/Twist_Myeloid/Bed_files/HG38/Twist_myeloid_TE-96463385_hg38_241211.bed"
  design_intervals: "/projects/wp2/nobackup/Twist_Myeloid/Bed_files/HG38/Twist_myeloid_TE-96463385_hg38_241211.interval_list" #hsmetrics
  design_intervals_gatk_cnv: "/projects/wp2/nobackup/Twist_Myeloid/ReferenceFiles/Poppy_references_files/250129_NovaSeq/reference_files/design.preprocessed.interval_list" 
  artifacts: "/projects/wp2/nobackup/Twist_Myeloid/ReferenceFiles/Poppy_references_files/250129_NovaSeq/reference_files/artifact_panel.tsv"
  artifacts_pindel: "/projects/wp2/nobackup/Twist_Myeloid/ReferenceFiles/Poppy_references_files/250129_NovaSeq/reference_files/artifact_panel_pindel.tsv"
  background: "/projects/wp2/nobackup/Twist_Myeloid/ReferenceFiles/Poppy_references_files/250129_NovaSeq/reference_files/background_panel.tsv"
  skip_chrs:
    - "chrM"
    - "chr1_KI270706v1_random"
    - "chr1_KI270707v1_random"
    - "chr1_KI270708v1_random"
    - "chr1_KI270709v1_random"
    - "chr1_KI270710v1_random"
    - "chr1_KI270711v1_random"
    - "chr1_KI270712v1_random"
    - "chr1_KI270713v1_random"
    - "chr1_KI270714v1_random"
    - "chr2_KI270715v1_random"
    - "chr2_KI270716v1_random"
    - "chr3_GL000221v1_random"
    - "chr4_GL000008v2_random"
    - "chr5_GL000208v1_random"
    - "chr9_KI270717v1_random"
    - "chr9_KI270718v1_random"
    - "chr9_KI270719v1_random"
    - "chr9_KI270720v1_random"
    - "chr11_KI270721v1_random"
    - "chr14_GL000009v2_random"
    - "chr14_GL000225v1_random"
    - "chr14_KI270722v1_random"
    - "chr14_GL000194v1_random"
    - "chr14_KI270723v1_random"
    - "chr14_KI270724v1_random"
    - "chr14_KI270725v1_random"
    - "chr14_KI270726v1_random"
    - "chr15_KI270727v1_random"
    - "chr16_KI270728v1_random"
    - "chr17_GL000205v2_random"
    - "chr17_KI270729v1_random"
    - "chr17_KI270730v1_random"
    - "chr22_KI270731v1_random"
    - "chr22_KI270732v1_random"
    - "chr22_KI270733v1_random"
    - "chr22_KI270734v1_random"
    - "chr22_KI270735v1_random"
    - "chr22_KI270736v1_random"
    - "chr22_KI270737v1_random"
    - "chr22_KI270738v1_random"
    - "chr22_KI270739v1_random"
    - "chrY_KI270740v1_random"
    - "chrUn_KI270302v1"
    - "chrUn_KI270304v1"
    - "chrUn_KI270303v1"
    - "chrUn_KI270305v1"
    - "chrUn_KI270322v1"
    - "chrUn_KI270320v1"
    - "chrUn_KI270310v1"
    - "chrUn_KI270316v1"
    - "chrUn_KI270315v1"
    - "chrUn_KI270312v1"
    - "chrUn_KI270311v1"
    - "chrUn_KI270317v1"
    - "chrUn_KI270412v1"
    - "chrUn_KI270411v1"
    - "chrUn_KI270414v1"
    - "chrUn_KI270419v1"
    - "chrUn_KI270418v1"
    - "chrUn_KI270420v1"
    - "chrUn_KI270424v1"
    - "chrUn_KI270417v1"
    - "chrUn_KI270422v1"
    - "chrUn_KI270423v1"
    - "chrUn_KI270425v1"
    - "chrUn_KI270429v1"
    - "chrUn_KI270442v1"
    - "chrUn_KI270466v1"
    - "chrUn_KI270465v1"
    - "chrUn_KI270467v1"
    - "chrUn_KI270435v1"
    - "chrUn_KI270438v1"
    - "chrUn_KI270468v1"
    - "chrUn_KI270510v1"
    - "chrUn_KI270509v1"
    - "chrUn_KI270518v1"
    - "chrUn_KI270508v1"
    - "chrUn_KI270516v1"
    - "chrUn_KI270512v1"
    - "chrUn_KI270519v1"
    - "chrUn_KI270522v1"
    - "chrUn_KI270511v1"
    - "chrUn_KI270515v1"
    - "chrUn_KI270507v1"
    - "chrUn_KI270517v1"
    - "chrUn_KI270529v1"
    - "chrUn_KI270528v1"
    - "chrUn_KI270530v1"
    - "chrUn_KI270539v1"
    - "chrUn_KI270538v1"
    - "chrUn_KI270544v1"
    - "chrUn_KI270548v1"
    - "chrUn_KI270583v1"
    - "chrUn_KI270587v1"
    - "chrUn_KI270580v1"
    - "chrUn_KI270581v1"
    - "chrUn_KI270579v1"
    - "chrUn_KI270589v1"
    - "chrUn_KI270590v1"
    - "chrUn_KI270584v1"
    - "chrUn_KI270582v1"
    - "chrUn_KI270588v1"
    - "chrUn_KI270593v1"
    - "chrUn_KI270591v1"
    - "chrUn_KI270330v1"
    - "chrUn_KI270329v1"
    - "chrUn_KI270334v1"
    - "chrUn_KI270333v1"
    - "chrUn_KI270335v1"
    - "chrUn_KI270338v1"
    - "chrUn_KI270340v1"
    - "chrUn_KI270336v1"
    - "chrUn_KI270337v1"
    - "chrUn_KI270363v1"
    - "chrUn_KI270364v1"
    - "chrUn_KI270362v1"
    - "chrUn_KI270366v1"
    - "chrUn_KI270378v1"
    - "chrUn_KI270379v1"
    - "chrUn_KI270389v1"
    - "chrUn_KI270390v1"
    - "chrUn_KI270387v1"
    - "chrUn_KI270395v1"
    - "chrUn_KI270396v1"
    - "chrUn_KI270388v1"
    - "chrUn_KI270394v1"
    - "chrUn_KI270386v1"
    - "chrUn_KI270391v1"
    - "chrUn_KI270383v1"
    - "chrUn_KI270393v1"
    - "chrUn_KI270384v1"
    - "chrUn_KI270392v1"
    - "chrUn_KI270381v1"
    - "chrUn_KI270385v1"
    - "chrUn_KI270382v1"
    - "chrUn_KI270376v1"
    - "chrUn_KI270374v1"
    - "chrUn_KI270372v1"
    - "chrUn_KI270373v1"
    - "chrUn_KI270375v1"
    - "chrUn_KI270371v1"
    - "chrUn_KI270448v1"
    - "chrUn_KI270521v1"
    - "chrUn_GL000195v1"
    - "chrUn_GL000219v1"
    - "chrUn_GL000220v1"
    - "chrUn_GL000224v1"
    - "chrUn_KI270741v1"
    - "chrUn_GL000226v1"
    - "chrUn_GL000213v1"
    - "chrUn_KI270743v1"
    - "chrUn_KI270744v1"
    - "chrUn_KI270745v1"
    - "chrUn_KI270746v1"
    - "chrUn_KI270747v1"
    - "chrUn_KI270748v1"
    - "chrUn_KI270749v1"
    - "chrUn_KI270750v1"
    - "chrUn_KI270751v1"
    - "chrUn_KI270752v1"
    - "chrUn_KI270753v1"
    - "chrUn_KI270754v1"
    - "chrUn_KI270755v1"
    - "chrUn_KI270756v1"
    - "chrUn_KI270757v1"
    - "chrUn_GL000214v1"
    - "chrUn_KI270742v1"
    - "chrUn_GL000216v2"
    - "chrUn_GL000218v1"
    - "chrEBV"

annotate_cnv:
  cnv_genes: "/projects/wp2/nobackup/Twist_Myeloid/Bed_files/HG38/Twist_myeloid_cnv_annotation.240227.bed"

bamsnap:
  extra: " -coverage_vaf 0.05 -show_soft_clipped -read_thickness 2 -read_gap_height 1 "
  container: "docker://hydragenetics/bamsnap:0.2.19"

bcftools_annotate:
  annotation_db: /data/ref_genomes/GNOMAD/small_exac_common_3.hg38.vcf.gz

bcftools_concat_vcfs:
  extra: " -a "

bcftools_filter_include_region:
  cll: "/projects/wp2/nobackup/Twist_Myeloid/Bed_files/HG38/CLL_genes_for_xlsx.250114.sorted.bed"
  myeloid: "/projects/wp2/nobackup/Twist_Myeloid/Bed_files/HG38/Myeloid_genes_for_xlsx.250114.sorted.bed"
  hotspot: "/projects/wp2/nobackup/Twist_Myeloid/Bed_files/HG38/hotspot_genes_for_xlsx.250602.sorted.bed"

bwa_mem:
  amb: "/data/ref_genomes/GRCh38/GRCmasked/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.amb"
  ann: "/data/ref_genomes/GRCh38/GRCmasked/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.ann"
  bwt: "/data/ref_genomes/GRCh38/GRCmasked/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.bwt"
  pac: "/data/ref_genomes/GRCh38/GRCmasked/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.pac"
  sa: "/data/ref_genomes/GRCh38/GRCmasked/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.sa"

cnv_html_report:
  cytobands: true
  show_table: true

cnvkit_batch:
  normal_reference: "/projects/wp2/nobackup/Twist_Myeloid/ReferenceFiles/Poppy_references_files/250129_NovaSeq/reference_files/cnvkit.PoN.cnn"
  method: hybrid

filter_vcf:
  sample_name_regex: ^([A-Za-z0-9-]+_[NRT]\{1\})$
  germline: "{{POPPY_UU_HOME}}/config/filters/config_hard_filter_germline.yaml"
  somatic: "{{POPPY_UU_HOME}}/config/filters/config_soft_filter_somatic.yaml"
  somatic_hard: "{{POPPY_UU_HOME}}/config/filters/config_hard_filter_somatic.yaml"
  pindel: "{{POPPY_UU_HOME}}/config/filters/config_soft_filter_pindel.yaml"
  cnv_hard_filter: "{{POPPY_UU_HOME}}/config/filters/config_hard_filter_cnv.yaml"

gatk_collect_allelic_counts:
  SNP_interval: "/projects/wp2/nobackup/Twist_Myeloid/Bed_files/HG38/Twist_myeloid_cnv100.241211.interval_list"

gatk_denoise_read_counts:
  normal_reference: "/projects/wp2/nobackup/Twist_Myeloid/ReferenceFiles/Poppy_references_files/250129_NovaSeq/reference_files/gatk.PoN.hdf5"

merge_af_complex_variants:
  merge_method: "sum" 

merge_cnv_json:
  cytobands: "{{POPPY_UU_HOME}}/config/cytoBand.hg38.txt"
  annotations:
    - "/projects/wp2/nobackup/Twist_Myeloid/Bed_files/HG38/Twist_myeloid_cnv_annotation.240227.bed" 
  germline_vcf: snv_indels/bcbio_variation_recall_ensemble/{sample}_{type}.ensembled.vep_annotated.filter.germline.vcf.gz
  filtered_cnv_vcfs:
    - cnv_sv/svdb_query/{sample}_{type}.{tc_method}.svdb_query.annotate_cnv.cnv_genes.filter.cnv_hard_filter.vcf.gz
  unfiltered_cnv_vcfs:
    - cnv_sv/svdb_query/{sample}_{type}.{tc_method}.svdb_query.annotate_cnv.cnv_genes.vcf.gz

multiqc:
  reports:
    DNA:
      config: "{{POPPY_UU_HOME}}/config/config_multiqc.yaml"
      qc_files:
        - "qc/fastqc/{sample}_{type}_{flowcell}_{lane}_{barcode}_{read}_fastqc.zip"
        - "prealignment/fastp_pe/{sample}_{type}_{flowcell}_{lane}_{barcode}_fastp.json"
        - "qc/mosdepth_bed_coding/{sample}_{type}.mosdepth.summary.txt"
        - "qc/mosdepth_bed_coding/{sample}_{type}.per-base.bed.gz"
        - "qc/mosdepth_bed_coding/{sample}_{type}.mosdepth.region.dist.txt"
        - "qc/mosdepth_bed_coding/{sample}_{type}.regions.bed.gz"
        - "qc/mosdepth_bed_coding/{sample}_{type}.thresholds.bed.gz"
        - "qc/picard_collect_hs_metrics/{sample}_{type}.HsMetrics.txt"
        - "qc/picard_collect_alignment_summary_metrics/{sample}_{type}.alignment_summary_metrics.txt" #inga general stats
        - "qc/picard_collect_duplication_metrics/{sample}_{type}.duplication_metrics.txt"
        - "qc/picard_collect_insert_size_metrics/{sample}_{type}.insert_size_metrics.txt"
        - "qc/picard_collect_gc_bias_metrics/{sample}_{type}.gc_bias.summary_metrics"
        - "qc/samtools_stats/{sample}_{type}.samtools-stats.txt"
        - "versions/update_poppy.temp"

pindel_call:
  extra: "-x 2 -B 60" #x och B?
  include_bed: "/projects/wp2/nobackup/Twist_Myeloid/Bed_files/HG38/Twist_myeloid_pindel_240628.bed"

pindel2vcf:
  extra: "-e 10 -mc 10 -is 5 -he 0.01 -G" # num reads support
  refname: "GCA_000001405.15_GRCh38_no_alt"
  refdate: "2022"

purecn:
  genome: GRCh38
  normaldb: "/projects/wp2/nobackup/Twist_Myeloid/ReferenceFiles/Poppy_references_files/250129_NovaSeq/reference_files/purecn_normal_db.rds"
  intervals: "/projects/wp2/nobackup/Twist_Myeloid/ReferenceFiles/Poppy_references_files/250129_NovaSeq/reference_files/purecn_targets_intervals.txt"
  mapping_bias_file: "/projects/wp2/nobackup/Twist_Myeloid/ReferenceFiles/Poppy_references_files/250129_NovaSeq/reference_files/purecn_mapping_bias.rds"

purecn_coverage:
  intervals: "/projects/wp2/nobackup/Twist_Myeloid/ReferenceFiles/Poppy_references_files/250129_NovaSeq/reference_files/purecn_targets_intervals.txt"

results_report_xlsx:
  wanted_transcripts: "/projects/wp2/nobackup/Twist_Myeloid/Bed_files/HG38/tm_mane_transcript.240404.txt"

svdb_query:
  db_string: "--db /projects/wp2/nobackup/Twist_Myeloid/ReferenceFiles/Poppy_references_files/250129_NovaSeq/reference_files/svdb_cnv.vcf --out_frq Normal_AF --out_occ Normal_NovaSeq"

vep:
  vep_cache: "/data/ref_genomes/VEP"
