default_resources:
  threads: 1
  time: "01:00:00"
  mem_mb: 6144
  mem_per_cpu: 6144
  partition: core_bkup,core

bwa_mem:
  threads: 20
  mem_mb: 122880
  time: "12:00:00"

fastp_pe:
  threads: 5
  mem_mb: 30720

fastqc:
  threads: 10
  mem_mb: 61440
  time: "02:00:00"

picard_collect_gc_bias_metrics:
  mem_mb: 30720
  threads: 5

gatk_collect_allelic_counts:
  mem_mb: 30720
  threads: 5

bamsnap:
  time: "05:00:00"
  threads: 1
  mem_mb: 6144
